#Requires -Version 5.1
<#
  ERP v4.1 Supabase backup — one-click setup (config + test + scheduled task)
  Run as Administrator on company server:
    cd D:\ERP\docs
    .\ERPv4.1_Supabase-backup-setup.ps1

  Optional: -Env PROD | DEV   (default PROD, affects task name only)
#>
param(
  [ValidateSet("PROD", "DEV")]
  [string]$Env = "PROD",
  [switch]$SkipTest,
  [switch]$SkipSchedule
)

$ErrorActionPreference = "Stop"

function Write-Step([string]$msg) {
  Write-Host "[ERP-Backup-Setup] $msg" -ForegroundColor Cyan
}

function Write-Ok([string]$msg) {
  Write-Host "[ERP-Backup-Setup] $msg" -ForegroundColor Green
}

function Write-Warn([string]$msg) {
  Write-Host "[ERP-Backup-Setup] $msg" -ForegroundColor Yellow
}

function Find-PgDump {
  $candidates = @(
    "D:\pgsql\17\bin\pg_dump.exe",
    "D:\pgsql\16\bin\pg_dump.exe",
    "C:\pgsql\17\bin\pg_dump.exe",
    "C:\pgsql\16\bin\pg_dump.exe"
  )
  foreach ($p in $candidates) {
    if (Test-Path -LiteralPath $p) { return $p }
  }
  $cmd = Get-Command pg_dump -ErrorAction SilentlyContinue
  if ($cmd -and (Test-Path -LiteralPath $cmd.Source)) { return $cmd.Source }
  return ""
}

function Read-DotEnvValue([string]$filePath, [string]$key) {
  if (-not (Test-Path -LiteralPath $filePath)) { return "" }
  foreach ($line in Get-Content -LiteralPath $filePath -Encoding UTF8) {
    $t = $line.Trim()
    if (-not $t -or $t.StartsWith("#")) { continue }
    if ($t -match ("^\s*" + [regex]::Escape($key) + "\s*=\s*(.+)\s*$")) {
      return $Matches[1].Trim().Trim('"').Trim("'")
    }
  }
  return ""
}

function Get-ProjectRefFromSupabaseUrl([string]$url) {
  if (-not $url) { return "" }
  if ($url -match "https?://([a-z0-9]+)\.supabase\.co") {
    return $Matches[1]
  }
  return ""
}

function Escape-SingleQuoted([string]$s) {
  if ($null -eq $s) { return "" }
  return ($s -replace "'", "''")
}

function Write-BackupConfigFile([hashtable]$cfg, [string]$path) {
  $content = @"
# Generated by ERPv4.1_Supabase-backup-setup.ps1 — do not commit

`$BackupConfig = @{
  DbHost     = "$($cfg.DbHost)"
  DbPort     = $($cfg.DbPort)
  DbName     = "$($cfg.DbName)"
  DbUser     = "$($cfg.DbUser)"
  DbPassword = '$(Escape-SingleQuoted $cfg.DbPassword)'
  PgDumpPath = "$($cfg.PgDumpPath)"
  OutDir     = "$($cfg.OutDir)"
  KeepDays   = $($cfg.KeepDays)
}
"@
  Set-Content -LiteralPath $path -Value $content -Encoding UTF8
}

$scriptDir = $PSScriptRoot
$backupPs1 = Join-Path $scriptDir "ERPv4.1_Supabase-backup.ps1"
$configPath = Join-Path $scriptDir "ERPv4.1_Supabase-backup.config.ps1"
$serverEnv = Join-Path (Split-Path $scriptDir -Parent) "server\.env"
$taskName = "ERP-Supabase-Backup-$Env"

if (-not (Test-Path -LiteralPath $backupPs1)) {
  throw "Backup script not found: $backupPs1"
}

Write-Step "ERP v4.1 Supabase backup setup ($Env)"
Write-Step "Script dir: $scriptDir"

$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
  [Security.Principal.WindowsBuiltInRole]::Administrator
)
if (-not $SkipSchedule -and -not $isAdmin) {
  Write-Warn "Not running as Administrator. Scheduled task will be skipped."
  Write-Warn "Re-run this script in Admin PowerShell to register daily 00:00 task."
  $SkipSchedule = $true
}

$pgDumpPath = Find-PgDump
if (-not $pgDumpPath) {
  Write-Warn "pg_dump not found."
  Write-Host ""
  Write-Host "Install PostgreSQL 17 binaries first:" -ForegroundColor Yellow
  Write-Host "  https://www.enterprisedb.com/downloads/postgres-postgresql-downloads" -ForegroundColor Yellow
  Write-Host "  Extract to D:\pgsql\17\  then re-run this script." -ForegroundColor Yellow
  Write-Host ""
  $pgDumpPath = Read-Host "Or paste full path to pg_dump.exe now (Enter to exit)"
  if (-not $pgDumpPath -or -not (Test-Path -LiteralPath $pgDumpPath)) {
    throw "pg_dump is required."
  }
} else {
  Write-Ok ("Found pg_dump: " + $pgDumpPath)
}

$supabaseUrl = Read-DotEnvValue $serverEnv "SUPABASE_URL"
$projectRef = Get-ProjectRefFromSupabaseUrl $supabaseUrl
$suggestedUser = ""
if ($projectRef) {
  $suggestedUser = "postgres." + $projectRef
  Write-Ok ("From server\.env SUPABASE_URL -> DbUser suggestion: " + $suggestedUser)
}

$defaultHost = "aws-0-ap-northeast-1.pooler.supabase.com"
$defaultOut = "D:\ERP-Backup\supabase"

Write-Host ""
Write-Host "Enter Supabase Database connection (Session pooler):" -ForegroundColor White
Write-Host "  Dashboard -> Project Settings -> Database -> Connection string -> Session pooler" -ForegroundColor DarkGray
Write-Host ""

$hostInput = Read-Host ("DbHost [$defaultHost]")
$dbHost = if ($hostInput) { $hostInput.Trim() } else { $defaultHost }

$userPrompt = "DbUser"
if ($suggestedUser) { $userPrompt += " [$suggestedUser]" }
$userInput = Read-Host $userPrompt
$dbUser = if ($userInput) { $userInput.Trim() } elseif ($suggestedUser) { $suggestedUser } else {
  throw "DbUser is required (postgres.projectref)."
}

$dbPass = Read-Host "DbPassword (Database password, input hidden)" -AsSecureString
$dbPassPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
  [Runtime.InteropServices.Marshal]::SecureStringToBSTR($dbPass)
)
if (-not $dbPassPlain) { throw "DbPassword is required." }

$outInput = Read-Host ("OutDir [$defaultOut]")
$outDir = if ($outInput) { $outInput.Trim() } else { $defaultOut }

$cfg = @{
  DbHost     = $dbHost
  DbPort     = 5432
  DbName     = "postgres"
  DbUser     = $dbUser
  DbPassword = $dbPassPlain
  PgDumpPath = $pgDumpPath
  OutDir     = $outDir
  KeepDays   = 0
}

Write-BackupConfigFile $cfg $configPath
Write-Ok ("Wrote config: " + $configPath)

if (-not $SkipTest) {
  Write-Step "Running test backup..."
  & $backupPs1 -ConfigPath $configPath
  Write-Ok "Test backup OK."
}

if (-not $SkipSchedule) {
  Write-Step ("Registering scheduled task: " + $taskName)
  $arg = '-NoProfile -ExecutionPolicy Bypass -File "' + $backupPs1 + '"'
  $existing = Get-ScheduledTask -TaskName $taskName -ErrorAction SilentlyContinue
  if ($existing) {
    Unregister-ScheduledTask -TaskName $taskName -Confirm:$false
  }
  $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $arg
  $trigger = New-ScheduledTaskTrigger -Daily -At "00:00"
  $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest | Out-Null
  Write-Ok ("Scheduled task created: daily 00:00, run ASAP if missed.")
}

Write-Host ""
Write-Ok "Setup complete."
Write-Host "  Config : $configPath" -ForegroundColor DarkGray
Write-Host "  OutDir : $outDir" -ForegroundColor DarkGray
if (-not $SkipSchedule) {
  Write-Host "  Task   : $taskName" -ForegroundColor DarkGray
}
Write-Host "  Help   : $((Split-Path $scriptDir -Parent))\Supabase每日備份-說明.txt" -ForegroundColor DarkGray
